<a href="https://colab.research.google.com/github/hokoro/Big-Data-Statistics-Analysis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 넘파이 기본 선언 

In [6]:
import numpy as np 
a = [[1,2,3],[4,5,6]]
b = np.array(a)
print(a)
print(b)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


#### 넘파이 배열의 기본정보 보는 방법


In [7]:
print(b.ndim) #배열의 기본 차원 정보 
print(b.shape)#배열의 모양 
print(b[:,:-1]) 
print(len(b)) #행의 길이
print(len(b[0]))#열의 길이
print(b.size) #전체 데이터 개수
print(b.dtype) # 데이터 타입
b.astype(float) #넘파이 데이터 타입 변경


2
(2, 3)
[[1 2]
 [4 5]]
2
3
6
int64


array([[1., 2., 3.],
       [4., 5., 6.]])

####배열 연산

In [18]:
x = np.array([[1,2],[3,4]] , dtype = np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

print(np.add(x,y)) # 더하기
print(np.subtract(x,y)) #빼기
print(np.multiply(x,y)) #곱하기 
print(np.divide(x,y)) #나누기
print(np.sqrt(x)) #제곱근 
print(np.log(x)) #log값
print(np.exp(x)) #자연상수 값
print(np.dot(x,y)) #행렬곱

print(x==y) #행렬의 원소 비교 
print(np.array_equal(x,y))

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[0.         0.69314718]
 [1.09861229 1.38629436]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[19. 22.]
 [43. 50.]]
[[False False]
 [False False]]
False


#### 집계 함수

In [24]:
print(x.sum())
print(x.sum(axis = 0)) #열의 합계
print(x.sum(axis = 1)) #행의 합계 


print(x.min())
print(x.min(axis = 0)) #열의 최소값
print(x.min(axis = 1)) #행의 최소값

print(x.max())
print(x.max(axis = 0)) #열의 최대값
print(x.max(axis = 1)) #행의 최대값

10.0
[4. 6.]
[3. 7.]
1.0
[1. 2.]
[1. 3.]
4.0
[3. 4.]
[2. 4.]


In [25]:
print(x.cumsum())
print(x.cumsum(axis = 0)) #열의 누적합
print(x.cumsum(axis = 1)) #행의 누적합

[ 1.  3.  6. 10.]
[[1. 2.]
 [4. 6.]]
[[1. 3.]
 [3. 7.]]


In [26]:
print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))

2.5
2.5
1.25
1.118033988749895


In [27]:
c = np.array([1,2,3])
d = np.array([[1,2,3],[4,5,6]])


In [28]:
print(c[2])
print(d[1,2])

3
6


In [29]:
print(c[c<3]) #boolean 값으로 indexing 


[1 2]


In [30]:
np.zeros([3,3]) # 3,3 짜리 0 인 데이터 numpy  

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones([3,3]) # 3,3 짜리 전부 1인 데이터 numpy

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.arange(5) #해당 숫자 아래로 1차원 배열 생성
np.arange(5,20,3) #stub 을 줘서 numpy 생성 가능 


array([ 5,  8, 11, 14, 17])

In [36]:
np.linspace(0,2,9) #0 ~ 2 까지 9등분 하여 numpy 배열 생성                           

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [37]:
np.full([3,3],7) # 7로 3x3 넘파이 배열에 숫자 채우기

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [38]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [39]:
b = np.array([[1.5,2,3],[4,5,6]])

print(np.transpose(b)) #행과 열을 바꾸는 전치 행렬 
print(b.T)

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]
[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]


In [40]:
print(b.ravel()) #1차원 배열로 나열하는 ravel

[1.5 2.  3.  4.  5.  6. ]


In [41]:
b.reshape([3,2])

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [42]:
np.vstack([x,y]) #numpy 와 numpy 배열 끼리 합치기 

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [43]:
np.c_[x,y]

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])